name: Build/release

on: push

jobs:
  release:
    runs-on: macos-latest

    # strategy:
    #   matrix:
    #     os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Release Build
        run: npm run release