name: Publish Release

on:
    push:
      tags:
        - 'v*'

jobs:
  build_and_release:

    # runs-on: ${{ matrix.os }}
    runs-on: macos-latest

    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm ci

      - name: Build MacOS App
        if: matrix.os == 'macos-latest' 
        run: npm run release:macos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Build Windows App
      #   if: matrix.os == 'windows-latest'
      #   run: npm run release:windows
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Build Linux App
      #   if: matrix.os == 'linux-latest'
      #   run: npm run release:linux
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Upload binaries to release
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GH_TOKEN }}
            file: ./build/XWarp-Mac-1.0.0-Installer.dmg
            asset_name: ./build/XWarp-Mac-1.0.0-Installer.dmg
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: true
